blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/hooleeas/subconverter-new/blob/master/README.md
    about: Please read the project documentation before opening an issue.
